services:
    frontend:
        build:
            context: ./chat-base
        container_name: chat-frontend
        volumes:
            - /app/chat-base/node_modules ## anonymous volume for node_modules
            - ./chat-base:/app/chat-base
        ports:
            - 5179:5179
        networks:
            - default
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
        container_name: chat-backend
        volumes:
            - ./backend:/app/backend
        ports:
            - 8008:8008
        networks:
            - default
networks:
    default:
        name: chat-network
        driver: bridge
