services:
    backend:
        build:
            context: ./backend
        container_name: chat-backend
        volumes:
            - ./backend:/app/backend
        ports:
            - 8008:8008
        env_file:
            - ./backend/.env
        networks:
            - default
networks:
    default:
        name: chat-network
        driver: bridge
