FROM python:3.12.2

# set the working directory
WORKDIR /chatui-base/backend

# copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy the current directory to the working directory
COPY . .

EXPOSE 8018

# command to run the server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8018"]



