"""Added many to one relationship betweeen message and llm table

Revision ID: 164db53385bd
Revises: 176fcc7fb9db
Create Date: 2024-04-23 16:41:53.613822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164db53385bd'
down_revision: Union[str, None] = '176fcc7fb9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('llm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'llm', ['llm_id'], ['id'])
    op.drop_column('message', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'llm_id')
    # ### end Alembic commands ###
