"""added cols to message, added new llm table for prices

Revision ID: 176fcc7fb9db
Revises: 1a750bbcf5a7
Create Date: 2024-04-23 15:23:44.209910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176fcc7fb9db'
down_revision: Union[str, None] = '1a750bbcf5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens_cost', sa.Float(), nullable=False),
    sa.Column('completion_tokens_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('model', sa.String(), nullable=True))
    op.add_column('message', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'cost')
    op.drop_column('message', 'model')
    op.drop_column('message', 'completion_tokens')
    op.drop_column('message', 'prompt_tokens')
    op.drop_table('llm')
    # ### end Alembic commands ###
