"""added conv, message and user table along with relationships

Revision ID: 1a750bbcf5a7
Revises: b47f79b60f9d
Create Date: 2024-03-20 16:07:43.582205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a750bbcf5a7'
down_revision: Union[str, None] = 'b47f79b60f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('message', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('message', sa.Column('role', sa.String(), nullable=False))
    op.add_column('message', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('message', sa.Column('conv_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'conversation', ['conv_id'], ['id'])
    op.drop_column('message', 'sender')
    op.drop_column('message', 'message')
    op.drop_column('message', 'updatedAt')
    op.drop_column('message', 'createdAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'conv_id')
    op.drop_column('message', 'content')
    op.drop_column('message', 'role')
    op.drop_column('message', 'updated_at')
    op.drop_column('message', 'created_at')
    op.drop_table('conversation')
    op.drop_table('user')
    # ### end Alembic commands ###
