name: Continuous deployment of frontend to digital ocean production

on:
    push:
        branches:
            - staging
        paths:
            - "chat-base/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install dependencies
              working-directory: ./chat-base
              run: npm ci

            - name: Build
              working-directory: ./chat-base
              run: npm run build:staging

            - name: Deploy to server via SSH
              uses: easingthemes/ssh-deploy@v5.0.3
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: "-avz --delete"
                  SOURCE: "./chat-base/dist/"
                  REMOTE_HOST: ${{ vars.REMOTE_HOST }}
                  REMOTE_USER: ${{ vars.REMOTE_USER }}
                  TARGET: "/usr/share/nginx/html-staging"

            - name: reload nginx inside Digital Ocean
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ vars.REMOTE_HOST }}
                  username: ${{ vars.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      nginx -s reload
                      echo "[FE] Prod github action succeeded" >> prod-git-action.log
